cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: us-east-1
    credentials:
      accessKey: 
      secretKey: 
    end-point: 
      uri: https://sqs.us-east-1.amazonaws.com/763258292230/MyFirstQueue
