cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: us-east-1
    credentials:
      accessKey: AKIA3DNN5JADMRCOKOFL
      secretKey: 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
    end-point: 
      uri: https://sqs.us-east-1.amazonaws.com/763258292230/MyFirstQueue